version: "3.7"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=wengxin0421@outlook.com
      - NGINX_PROXY_CONTAINER=nginx-proxy

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webgallery-backend
    restart: always
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=webgallery.vianvian.store
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=webgallery.vianvian.store
